x-django-app-env: &django-app-env
  environment:
    - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
    - CELERY_BROKER_HOST=${CELERY_BROKER_HOST}
    - CELERY_BROKER_PORT=${CELERY_BROKER_PORT}
    - CELERY_BROKER_USER=${CELERY_BROKER_USER}
    - CELERY_BROKER_PASSWORD=${CELERY_BROKER_PASSWORD}
    - DB_HOST=${DB_HOST}
    - DB_PORT=${DB_PORT}
    - DB_NAME=${DB_NAME}
    - DB_USER=${DB_USER}
    - DB_PASSWORD=${DB_PASSWORD}

services:
  web:
    build:
      context: .
      args:
        - ENVIRONMENT=dev
    image: django_web:dev
    container_name: django_web
    ports:
      - "8000:8000"
    <<: *django-app-env
    volumes:
      - .:/task_scheduler
    depends_on:
      - db
      - rabbitmq

  celery:
    image: django_web:dev
    container_name: celery_worker
    command: celery -A task_scheduler worker --loglevel=info
    <<: *django-app-env
    depends_on:
      - web
    volumes:
      - .:/task_scheduler

  db:
    image: pingcap/tidb:v7.1.6
    container_name: tidb
    ports:
      - "4000:4000"
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - TZ=UTC

  rabbitmq:
    image: rabbitmq:4.0.4-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${CELERY_BROKER_USER}
      - RABBITMQ_DEFAULT_PASS=${CELERY_BROKER_PASSWORD}
